from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.roles import is_valid_role
from app.core.security import (
    hash_password,
    validate_password_strength,
    verify_password,
)
from app.core.tokens import create_access_token
from app.models.user import User
from app.repositories.user_repository import (
    add_user,
    get_user_by_username,
    is_username_taken,
    normalize_email,
    normalize_username,
    update_last_login_at,
)


class AuthServiceError(ValueError):
    """Base error for auth service failures."""


class DuplicateUsernameError(AuthServiceError):
    """Raised when username is already used."""


class InvalidCredentialsError(AuthServiceError):
    """Raised when username or password is wrong."""


class InactiveUserError(AuthServiceError):
    """Raised when user exists but is inactive."""


class InvalidRoleError(AuthServiceError):
    """Raised when role is not supported."""


class WeakPasswordError(AuthServiceError):
    """Raised when password policy validation fails."""

    def __init__(self, errors: list[str]) -> None:
        self.errors = errors
        super().__init__(" ".join(errors))


@dataclass(frozen=True)
class LoginToken:
    """Login token response generated by auth service."""

    access_token: str
    token_type: str
    expires_in_minutes: int


def get_utc_now() -> datetime:
    """Return current UTC datetime."""

    return datetime.now(timezone.utc)


def create_user_with_password(
    db: Session,
    *,
    full_name: str,
    username: str,
    password: str,
    role: str,
    business_id: int | None = None,
    email: str | None = None,
    theme_preference: str | None = None,
    is_active: bool = True,
) -> User:
    """Create a user after validating role, username and password policy."""

    normalized_username = normalize_username(username)
    normalized_email = normalize_email(email)

    if not normalized_username:
        raise AuthServiceError("Kullanıcı adı boş olamaz.")

    if not full_name.strip():
        raise AuthServiceError("Ad soyad boş olamaz.")

    if not is_valid_role(role):
        raise InvalidRoleError("Geçersiz kullanıcı rolü.")

    password_errors = validate_password_strength(password)

    if password_errors:
        raise WeakPasswordError(password_errors)

    if is_username_taken(
        db=db,
        username=normalized_username,
        business_id=business_id,
    ):
        raise DuplicateUsernameError("Bu kullanıcı adı zaten kullanılıyor.")

    now = get_utc_now()

    user = User(
        business_id=business_id,
        full_name=full_name.strip(),
        email=normalized_email,
        username=normalized_username,
        password_hash=hash_password(password),
        role=role,
        theme_preference=theme_preference,
        is_active=is_active,
        last_login_at=None,
        created_at=now,
        updated_at=now,
    )

    return add_user(db=db, user=user)


def authenticate_user(
    db: Session,
    *,
    username: str,
    password: str,
    business_id: int | None = None,
) -> User:
    """Authenticate user by username and password."""

    user = get_user_by_username(
        db=db,
        username=username,
        business_id=business_id,
    )

    if user is None:
        raise InvalidCredentialsError("Kullanıcı adı veya şifre hatalı.")

    if not user.is_active:
        raise InactiveUserError("Kullanıcı pasif durumda.")

    if not verify_password(password, user.password_hash):
        raise InvalidCredentialsError("Kullanıcı adı veya şifre hatalı.")

    user.last_login_at = get_utc_now()
    user.updated_at = get_utc_now()

    return update_last_login_at(db=db, user=user)


def create_login_token_for_user(user: User) -> LoginToken:
    """Create access token for an authenticated user."""

    access_token = create_access_token(
        subject=str(user.id),
        role=user.role,
        business_id=user.business_id,
    )

    return LoginToken(
        access_token=access_token,
        token_type="bearer",
        expires_in_minutes=settings.access_token_expire_minutes,
    )
