from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.roles import is_valid_role
from app.core.security import (
    hash_password,
    validate_password_strength,
    verify_password,
)
from app.core.tokens import create_access_token
from app.models.user import User
from app.repositories.user_repository import (
    add_user,
    get_user_by_username,
    is_username_taken,
    normalize_email,
    normalize_username,
    update_last_login_at,
)
from app.services.audit_log_service import create_audit_log
from app.services.login_attempt_service import (
    LoginAttemptLockedError,
    assert_login_allowed,
    record_failed_login_attempt,
    record_successful_login_attempt,
)
from app.services.subscription_service import (
    BusinessSubscriptionExpiredError,
    BusinessSubscriptionInactiveError,
    BusinessSubscriptionNotFoundError,
    ensure_business_subscription_is_usable_for_login,
)


class AuthServiceError(ValueError):
    """Base error for auth service failures."""


class DuplicateUsernameError(AuthServiceError):
    """Raised when username is already used."""


class InvalidCredentialsError(AuthServiceError):
    """Raised when username or password is wrong."""


class InactiveUserError(AuthServiceError):
    """Raised when user exists but is inactive or cannot login safely."""


class InvalidRoleError(AuthServiceError):
    """Raised when role is not supported."""


class AccountTemporarilyLockedError(AuthServiceError):
    """Raised when login is temporarily locked."""

    def __init__(self, locked_until_utc: datetime) -> None:
        self.locked_until_utc = locked_until_utc
        super().__init__("Çok fazla hatalı giriş denemesi yapıldı.")


class WeakPasswordError(AuthServiceError):
    """Raised when password policy validation fails."""

    def __init__(self, errors: list[str]) -> None:
        self.errors = errors
        super().__init__(" ".join(errors))


@dataclass(frozen=True)
class LoginToken:
    """Login token response generated by auth service."""

    access_token: str
    token_type: str
    expires_in_minutes: int


def get_utc_now() -> datetime:
    """Return current UTC datetime."""

    return datetime.now(timezone.utc)


def create_user_with_password(
    db: Session,
    *,
    full_name: str,
    username: str,
    password: str,
    role: str,
    business_id: int | None = None,
    email: str | None = None,
    theme_preference: str | None = None,
    is_active: bool = True,
) -> User:
    """Create a user after validating role, username and password policy."""

    normalized_username = normalize_username(username)
    normalized_email = normalize_email(email)

    if not normalized_username:
        raise AuthServiceError("Kullanıcı adı boş olamaz.")

    if not full_name.strip():
        raise AuthServiceError("Ad soyad boş olamaz.")

    if not is_valid_role(role):
        raise InvalidRoleError("Geçersiz kullanıcı rolü.")

    password_errors = validate_password_strength(password)

    if password_errors:
        raise WeakPasswordError(password_errors)

    if is_username_taken(
        db=db,
        username=normalized_username,
        business_id=business_id,
    ):
        raise DuplicateUsernameError("Bu kullanıcı adı zaten kullanılıyor.")

    now = get_utc_now()

    user = User(
        business_id=business_id,
        full_name=full_name.strip(),
        email=normalized_email,
        username=normalized_username,
        password_hash=hash_password(password),
        role=role,
        theme_preference=theme_preference,
        is_active=is_active,
        last_login_at=None,
        created_at=now,
        updated_at=now,
    )

    return add_user(db=db, user=user)


def record_login_failure(
    db: Session,
    *,
    username: str,
    business_id: int | None,
    user: User | None,
    failure_reason: str,
    ip_address: str | None,
    user_agent: str | None,
) -> None:
    """Record failed login attempt and audit event."""

    normalized_username = normalize_username(username)
    effective_business_id = user.business_id if user is not None else business_id
    attempt_result = record_failed_login_attempt(
        db=db,
        username=normalized_username,
        business_id=effective_business_id,
        failure_reason=failure_reason,
        ip_address=ip_address,
        user_agent=user_agent,
    )

    create_audit_log(
        db=db,
        action="auth.login_failed",
        business_id=effective_business_id,
        user_id=user.id if user is not None else None,
        entity_type="user" if user is not None else "auth",
        entity_id=str(user.id) if user is not None else None,
        detail={
            "username": normalized_username,
            "failure_reason": failure_reason,
            "failed_count": attempt_result.failed_count,
            "locked_until_utc": (
                attempt_result.locked_until_utc.isoformat()
                if attempt_result.locked_until_utc is not None
                else None
            ),
        },
        ip_address=ip_address,
        user_agent=user_agent,
    )

    if attempt_result.locked_until_utc is not None:
        create_audit_log(
            db=db,
            action="auth.login_locked",
            business_id=effective_business_id,
            user_id=user.id if user is not None else None,
            entity_type="user" if user is not None else "auth",
            entity_id=str(user.id) if user is not None else None,
            detail={
                "username": normalized_username,
                "failed_count": attempt_result.failed_count,
                "locked_until_utc": attempt_result.locked_until_utc.isoformat(),
            },
            ip_address=ip_address,
            user_agent=user_agent,
        )


def record_subscription_login_block(
    db: Session,
    *,
    username: str,
    user: User,
    failure_reason: str,
    ip_address: str | None,
    user_agent: str | None,
) -> None:
    """
    Record login block caused by tenant subscription state.

    This is intentionally not counted as a password failure because the user may
    know the correct password while the business subscription is not usable.
    """

    normalized_username = normalize_username(username)

    create_audit_log(
        db=db,
        action="auth.login_blocked_subscription",
        business_id=user.business_id,
        user_id=user.id,
        entity_type="user",
        entity_id=str(user.id),
        detail={
            "username": normalized_username,
            "role": user.role,
            "failure_reason": failure_reason,
        },
        ip_address=ip_address,
        user_agent=user_agent,
    )


def ensure_authenticated_user_can_login(
    db: Session,
    *,
    username: str,
    user: User,
    ip_address: str | None,
    user_agent: str | None,
) -> None:
    """Validate post-password login rules before token creation."""

    try:
        ensure_business_subscription_is_usable_for_login(
            db=db,
            business_id=user.business_id,
        )
    except BusinessSubscriptionNotFoundError as exc:
        record_subscription_login_block(
            db=db,
            username=username,
            user=user,
            failure_reason="missing_business_subscription",
            ip_address=ip_address,
            user_agent=user_agent,
        )
        raise InactiveUserError("Kullanıcı giriş yapamaz.") from exc
    except BusinessSubscriptionInactiveError as exc:
        record_subscription_login_block(
            db=db,
            username=username,
            user=user,
            failure_reason="inactive_business_subscription",
            ip_address=ip_address,
            user_agent=user_agent,
        )
        raise InactiveUserError("Kullanıcı giriş yapamaz.") from exc
    except BusinessSubscriptionExpiredError:
        create_audit_log(
            db=db,
            action="auth.login_allowed_expired_subscription",
            business_id=user.business_id,
            user_id=user.id,
            entity_type="user",
            entity_id=str(user.id),
            detail={
                "username": normalize_username(username),
                "role": user.role,
                "reason": "expired_business_subscription_read_only_access",
            },
            ip_address=ip_address,
            user_agent=user_agent,
        )
        return


def authenticate_user(
    db: Session,
    *,
    username: str,
    password: str,
    business_id: int | None = None,
    ip_address: str | None = None,
    user_agent: str | None = None,
) -> User:
    """Authenticate user by username and password."""

    normalized_username = normalize_username(username)

    try:
        assert_login_allowed(
            db=db,
            username=normalized_username,
            business_id=business_id,
        )
    except LoginAttemptLockedError as exc:
        create_audit_log(
            db=db,
            action="auth.login_blocked",
            business_id=business_id,
            user_id=None,
            entity_type="auth",
            entity_id=None,
            detail={
                "username": normalized_username,
                "locked_until_utc": exc.locked_until_utc.isoformat(),
            },
            ip_address=ip_address,
            user_agent=user_agent,
        )
        raise AccountTemporarilyLockedError(exc.locked_until_utc) from exc

    user = get_user_by_username(
        db=db,
        username=normalized_username,
        business_id=business_id,
    )

    if user is None:
        record_login_failure(
            db=db,
            username=normalized_username,
            business_id=business_id,
            user=None,
            failure_reason="invalid_credentials",
            ip_address=ip_address,
            user_agent=user_agent,
        )
        raise InvalidCredentialsError("Kullanıcı adı veya şifre hatalı.")

    if not user.is_active:
        record_login_failure(
            db=db,
            username=normalized_username,
            business_id=business_id,
            user=user,
            failure_reason="inactive_user",
            ip_address=ip_address,
            user_agent=user_agent,
        )
        raise InactiveUserError("Kullanıcı pasif durumda.")

    if not verify_password(password, user.password_hash):
        record_login_failure(
            db=db,
            username=normalized_username,
            business_id=business_id,
            user=user,
            failure_reason="invalid_credentials",
            ip_address=ip_address,
            user_agent=user_agent,
        )
        raise InvalidCredentialsError("Kullanıcı adı veya şifre hatalı.")

    ensure_authenticated_user_can_login(
        db=db,
        username=normalized_username,
        user=user,
        ip_address=ip_address,
        user_agent=user_agent,
    )

    user.last_login_at = get_utc_now()
    user.updated_at = get_utc_now()

    update_last_login_at(db=db, user=user)

    record_successful_login_attempt(
        db=db,
        username=normalized_username,
        business_id=user.business_id,
        ip_address=ip_address,
        user_agent=user_agent,
    )

    create_audit_log(
        db=db,
        action="auth.login_success",
        business_id=user.business_id,
        user_id=user.id,
        entity_type="user",
        entity_id=str(user.id),
        detail={
            "username": normalized_username,
            "role": user.role,
        },
        ip_address=ip_address,
        user_agent=user_agent,
    )

    return user


def create_login_token_for_user(user: User) -> LoginToken:
    """Create access token for an authenticated user."""

    access_token = create_access_token(
        subject=str(user.id),
        role=user.role,
        business_id=user.business_id,
    )

    return LoginToken(
        access_token=access_token,
        token_type="bearer",
        expires_in_minutes=settings.access_token_expire_minutes,
    )