"""full baseline schema

Revision ID: 7f15391ac7c5
Revises: 
Create Date: 2026-05-19 14:29:33.683774
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '7f15391ac7c5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('default_timezone', sa.String(length=100), nullable=False),
    sa.Column('default_theme', sa.String(length=30), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_theme', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_staff_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_code'), 'packages', ['code'], unique=True)
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_table('business_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('feature_code', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'feature_code', name='uq_business_features_business_feature')
    )
    op.create_index(op.f('ix_business_features_business_id'), 'business_features', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_features_feature_code'), 'business_features', ['feature_code'], unique=False)
    op.create_index(op.f('ix_business_features_id'), 'business_features', ['id'], unique=False)
    op.create_table('business_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=80), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'module_code', name='uq_business_modules_business_module')
    )
    op.create_index(op.f('ix_business_modules_business_id'), 'business_modules', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_modules_id'), 'business_modules', ['id'], unique=False)
    op.create_index(op.f('ix_business_modules_module_code'), 'business_modules', ['module_code'], unique=False)
    op.create_table('consent_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_documents_business_id'), 'consent_documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_consent_documents_document_type'), 'consent_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_consent_documents_id'), 'consent_documents', ['id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('package_code', sa.String(length=80), nullable=False),
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('license_owner', sa.String(length=200), nullable=True),
    sa.Column('starts_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_lifetime', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['package_code'], ['packages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_business_id'), 'licenses', ['business_id'], unique=False)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_index(op.f('ix_licenses_package_code'), 'licenses', ['package_code'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('was_successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('locked_until_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_business_id'), 'login_attempts', ['business_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_created_at_utc'), 'login_attempts', ['created_at_utc'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_locked_until_utc'), 'login_attempts', ['locked_until_utc'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_index(op.f('ix_login_attempts_was_successful'), 'login_attempts', ['was_successful'], unique=False)
    op.create_table('setup_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_state_business_id'), 'setup_state', ['business_id'], unique=True)
    op.create_index(op.f('ix_setup_state_id'), 'setup_state', ['id'], unique=False)
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_task_categories_business_name')
    )
    op.create_index(op.f('ix_task_categories_business_id'), 'task_categories', ['business_id'], unique=False)
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('theme_preference', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='uq_users_business_email'),
    sa.UniqueConstraint('business_id', 'username', name='uq_users_business_username')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('late_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('on_time_completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_completion_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_business_id'), 'daily_reports', ['business_id'], unique=False)
    op.create_index(op.f('ix_daily_reports_generated_by_user_id'), 'daily_reports', ['generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('default_priority', sa.String(length=30), nullable=False),
    sa.Column('default_due_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_photo', sa.Boolean(), nullable=False),
    sa.Column('requires_location', sa.Boolean(), nullable=False),
    sa.Column('requires_manager_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_business_id'), 'task_templates', ['business_id'], unique=False)
    op.create_index(op.f('ix_task_templates_category_id'), 'task_templates', ['category_id'], unique=False)
    op.create_index(op.f('ix_task_templates_id'), 'task_templates', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_arrived_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_photo', sa.Boolean(), nullable=False),
    sa.Column('requires_location', sa.Boolean(), nullable=False),
    sa.Column('requires_manager_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_user_id'), 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_business_id'), 'tasks', ['business_id'], unique=False)
    op.create_index(op.f('ix_tasks_category_id'), 'tasks', ['category_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_by_user_id'), 'tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_document_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['consent_document_id'], ['consent_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'consent_document_id', name='uq_user_consents_user_document')
    )
    op.create_index(op.f('ix_user_consents_business_id'), 'user_consents', ['business_id'], unique=False)
    op.create_index(op.f('ix_user_consents_consent_document_id'), 'user_consents', ['consent_document_id'], unique=False)
    op.create_index(op.f('ix_user_consents_id'), 'user_consents', ['id'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('related_task_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_related_task_id'), 'notifications', ['related_task_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_business_id'), 'task_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_id'), 'task_events', ['id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_events_user_id'), 'task_events', ['user_id'], unique=False)
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=700), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['task_events.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attachments_business_id'), 'task_attachments', ['business_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_event_id'), 'task_attachments', ['event_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_id'), 'task_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_task_attachments_task_id'), 'task_attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_uploaded_by_user_id'), 'task_attachments', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Rollback migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_attachments_uploaded_by_user_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_task_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_event_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_business_id'), table_name='task_attachments')
    op.drop_table('task_attachments')
    op.drop_index(op.f('ix_task_events_user_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_business_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_task_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_consent_document_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_business_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_business_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_templates_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_category_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_business_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_generated_by_user_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_business_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories')
    op.drop_index(op.f('ix_task_categories_business_id'), table_name='task_categories')
    op.drop_table('task_categories')
    op.drop_index(op.f('ix_setup_state_id'), table_name='setup_state')
    op.drop_index(op.f('ix_setup_state_business_id'), table_name='setup_state')
    op.drop_table('setup_state')
    op.drop_index(op.f('ix_login_attempts_was_successful'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_locked_until_utc'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at_utc'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_business_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_licenses_package_code'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_business_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_consent_documents_id'), table_name='consent_documents')
    op.drop_index(op.f('ix_consent_documents_document_type'), table_name='consent_documents')
    op.drop_index(op.f('ix_consent_documents_business_id'), table_name='consent_documents')
    op.drop_table('consent_documents')
    op.drop_index(op.f('ix_business_modules_module_code'), table_name='business_modules')
    op.drop_index(op.f('ix_business_modules_id'), table_name='business_modules')
    op.drop_index(op.f('ix_business_modules_business_id'), table_name='business_modules')
    op.drop_table('business_modules')
    op.drop_index(op.f('ix_business_features_id'), table_name='business_features')
    op.drop_index(op.f('ix_business_features_feature_code'), table_name='business_features')
    op.drop_index(op.f('ix_business_features_business_id'), table_name='business_features')
    op.drop_table('business_features')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_code'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
